export const PRODUCTS_ACTION_TYPES = {
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  CURRENCY: "CURRENCY",
  ADD_TO_CART: "ADD_TO_CART",
  CHANGE_COUNT: "CHANGE_COUNT",
  CHANGE_ATTRIBUTE: "CHANGE_ATTRIBUTE",
  CHECKOUT: "CHECKOUT",
  SHOW_MINI_CART: "SHOW_MINI_CART"

};
